import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/developer.png'
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lighBulb from '../../public/images/svgs/spotlight.svg';
import TransitionEffect from '@/components/TransitionEffect';
import NoScrollLink from '@/components/NoScrollLink';

export default function Home() {
  return (
    <>
      <Head>
        <title>Portafolio | Ulises Sánchez</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light sm:items-start">
        <Layout className="!pt-0 md:!pt-16 sm:!pt-16">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image src={profilePic} alt="Desarrollador" className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText text="Desarrollando sueños con código." className="!text-6xl !text-left
                xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Como desarrollador, me dedico a convertir ideas en aplicaciones web innovadoras.
                Siéntase libre de explorar mis últimos proyectos y posts, que muestran mi experiencia codificando.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Cv Ulises Sánchez.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg
                  font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                  md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Currículum <LinkArrow className={"h-auto ml-1 !w-6 md:!w-4"} />
                </Link>
                <NoScrollLink
                  href="/contact"
                  title="Contactar"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                />
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div className="absolute right-8 bottom-16 inline-block w-24 md:hidden">
          <Image src={lighBulb} alt="Desarrollador" className="w-full h-auto" />
        </div>
      </main>
    </>
  )
}
